### ISSUE TITLE
Not importing files

### ISSUE THREAD

**Issue by Gourav1910** [daledesilva/obsidian_keep-import#5] opened 2023-06-25 07:49 UTC
It is importing jpg and png but when it comes to json it stop importing after 3 files. What to do?

**Comment by daledesilva** [comment] 2023-06-25 11:55
Are you able to send a screenshot of what the error log in the import pop up says?
It should hopefully specify a file and - and if it does, send that file too if that’s alright.

**Comment by Gourav1910** [comment] 2023-06-26 11:10
> Are you able to send a screenshot of what the error log in the import pop up says? It should hopefully specify a file and - and if it does, send that file too if that’s alright.

![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/c0219a95-6763-4eb8-8e10-f7497256c912)
After importing 3 files it just stop like this and hang the obsidian. Then I have to close and restart the obsidian. I imported jpg and png and all the files imported successfully. But when I import json this is what happening. I also tried importing 1000 files instead of all the files(over 3000) but still it is hanging. And I am not seeing any msg or what you have mentioned "error log in the import pop up" or may be I don't know where to look.

**Comment by daledesilva** [comment] 2023-06-26 12:43
Hmmm.. interesting. The error log isn't showing so it's crashing for a reason I haven't allowed for.
I need to error handle it better.

I suspect it might be to do with this bug:
https://github.com/daledesilva/obsidian_google-keep-import/issues/4

I know you said you'd tried only importing 1000 files, are you able to set up a test vault and import 100 files only. If you find it crashes, than halve that again until it doesn't crash... essentially, you want to try and find which file is giving the problem. If you can do that, you could send it to me and I could check what the issue is.

But failing that, I'll try and improve the general error handling before the next release so that it at least skips any problem file.

**Comment by Gourav1910** [comment] 2023-06-26 14:31
Hi, this time I skipped some notes which are starting with special characters and then I selected all the notes which is starting with dates and this time all the notes imported and skipped one note/file. 
![image_2023-06-26_19-31-34](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/80bb3b7b-67fa-4f19-975f-c9778574b88f)

After that, notes name starting with english letters started. So now I decided to choose only notes starting with letter 'A'. So I had 174 notes starting with letter 'A' and it imported 8 notes and then it stopped there and hang.
![image_2023-06-26_19-36-03](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/b73beeaa-4fac-4812-8a17-e3c6ee5d0053)

Then I only pick 1 file(9th file of letter A from where the importing stopped) only and this time it didn't import it. Then I picked 10th file and again it didn't import it.  
![image_2023-06-26_19-44-11](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/94757c53-34c8-4673-9ade-565f75618bf2)

But 11th file imported. So then I again selected all the remaining file starting with letter 'A' but this time again 15 files imported and then it again hang.
![image_2023-06-26_19-41-42](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/85653338-a9cd-4362-95b4-306ccfd2aaee)


This is the name of 9th file - "A trigger is needed to shift the dimension and rec.json"
This is the name of 10th file - "A wise man once said_ _You don_t have to be grea.__.json"


In second round when only 15 file imported then this is the name of 16th file which didn't imported - "Aapke opponent ko kabhi bhi aapko overestimate kar.json"

These names suggests that notes having no special characters are also getting rejected.

**Comment by daledesilva** [comment] 2023-06-27 14:34
Thanks for going through all that. Very detailed :)

Actually, the filenames won't be the issue as anything your filesystem supports so too will Obsidian. It's actually the text inside the json file that's likely causing the errors.

If you're able to, send the files through, otherwise, open them in a text editor and see if you can see any weird characters. They might be hard to spot though.

**Comment by Gourav1910** [comment] 2023-06-27 18:09
> Thanks for going through all that. Very detailed :)
> 
> Actually, the filenames won't be the issue as anything your filesystem supports so too will Obsidian. It's actually the text inside the json file that's likely causing the errors.
> 
> If you're able to, send the files through, otherwise, open them in a text editor and see if you can see any weird characters. They might be hard to spot though.

[A wise man once said_ _You don_t have to be grea.__.zip](https://github.com/daledesilva/obsidian_google-keep-import/files/11885829/A.wise.man.once.said_._You.don_t.have.to.be.grea.__.zip)

This is one of the file which got rejected. Github is not supporting json file so I converted it into a zip file. I don't know what should I see so if you find that error then it would be better. Thanks for the help.

**Comment by interceptor** [comment] 2023-07-06 14:41
I have issues as well importing json files. I have not figured out why it crashes, based on content.

**Comment by daledesilva** [comment] 2023-07-09 14:31
Hi @interceptor and @Gourav1910 .
Sorry for the delay on this. I haven't been able to fix the issue yet, however, I've adjusted the code so that it no longer hangs. It should continue with all other files and report the error and potential solution approaches to you.
Please let me know if you have any issues with it - You can update through the usual obsidian plugin repository.

@Gourav1910 Unfortunately that file you sent me works perfectly on my end. Are you on a mac or PC? And are you running a recent (or the latest) version of Obsidian?

**Comment by daledesilva** [comment] 2023-07-23 08:48
Hi again @interceptor and @Gourav1910 
I've not updated the plugin to 1.1.0 Let me know if the issues still persist.

**Comment by Gourav1910** [comment] 2023-07-23 21:36
> Hi again @interceptor and @Gourav1910 I've not updated the plugin to 1.1.0 Let me know if the issues still persist.

Hi, great update. This time it imported all the files except few but also didn't hang.
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/f421533a-d8e0-4a7d-a1e9-aff4b4ec344b)

As you can see in the screenshot I imported over 7500 files(all the files in the google keep zip) and then I think all the skipped files are html and 42 files are failed as well. Now I want the seperate list of those 42 or the failed files because I wanna know which notes it skipped so that atleast I can manually import the notes data by copy and pasting(if the problem can't be resolved).

**Comment by Gourav1910** [comment] 2023-07-23 22:15
> > Hi again @interceptor and @Gourav1910 I've not updated the plugin to 1.1.0 Let me know if the issues still persist.
> 
> Hi, great update. This time it imported all the files except few but also didn't hang. ![image](https://user-images.githubusercontent.com/101202140/255432197-f421533a-d8e0-4a7d-a1e9-aff4b4ec344b.png)
> 
> As you can see in the screenshot I imported over 7500 files(all the files in the google keep zip) and then I think all the skipped files are html and 42 files are failed as well. Now I want the seperate list of those 42 or the failed files because I wanna know which notes it skipped so that atleast I can manually import the notes data by copy and pasting(if the problem can't be resolved).

I checked the imported file and you did a great job by assigning all the labels as tags and all the different kind of tags such as color, pinned. 

In one of my note one png file is not rendering. May be it is one of the failed file.
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/373da89f-82f0-413d-bb30-fe6ffc556179)

I have few more suggestions for image handling(if possible).

1) So suppose if the image name is "image.png" then i want you to add an optional setting in the plugin settings in which we can decide the dimension of import image in the following format "image.png|x". Here x is a variable which will represent the value we put in the settings. For example, if x=400 the all the images (png/jpg) will be embeded in the respective notes as "image.png|400". This will make all the images in the desired size.

2) In various themes like minimal theme or anuppuchin theme if we embed image side by side then it render also side by side.
Like this,
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/9a4ea99d-f0c5-4baa-9015-ee223514dc22)

This is the source mode view of the note.
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/6a9e7e4e-68e1-4d89-84c8-80480bc94f1e)

So I want you to embed all the images side by side so that it will render in grid format in various themes. IF themes don't support this feature then it will render normally.

This is the example of size 200 and 7 images put side by side.
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/7d9f44dd-9392-4c43-b3fd-1ddb96ebee55)

Source mode view:
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/101202140/ea8a558c-8643-4124-b8dc-c355c61a8091)

You can notice images automatically shift to next line if space is not available for rendering. Or even if we open side pane or side window.

3) As you can see in the screenshot the images are not in equal height so if possible make it equal height.

I may be demanding too much. But I am just telling what I am looking for. (If possible)

**Comment by daledesilva** [comment] 2023-07-23 23:29
Really glad it worked for you @Gourav1910 !
Unfortunately you’re request regarding the image dimensions is out of scope for what I think this plug-in should do (it’s already pretty complex for an import plug-in 🤣)

I didn’t realise it was possible to specify display dimensions in embedding (or maybe it’s not?). If it is, perhaps someone will make another plug-in for you that can iterate through your files and adjust the sizes of the embeds. Try asking on the forum or discord.

In regard to your skipped and failed files, the output log you’ve shown a screenshot of is scrollable and will list all of them and describe why they were skipped or why they failed.
Unfortunately you can’t get that log back so if you want to check why now I’d suggest starting a temporary new vault and importing them again, then scroll down to have a look at the end.

I wanted to export that log as a note so it could be referred to later but didn’t get the chance. I’ll do it in the coming weeks if you’d prefer to wait.

In regard to the png that’s missing, yep, that’s likely one of the failed ones.

Lastly, thanks for using my plugin! Would love it if you could follow me on threads or twitter (should help you hear about the potential update too). My handle is @daledesilva
If you like generative art, I’m on instagram under the same handle.

**Closed as completed by daledesilva** 2023-07-23 23:29 UTC

**Comment by Gourav1910** [comment] 2023-07-24 01:14
> Really glad it worked for you @Gourav1910 ! Unfortunately you’re request regarding the image dimensions is out of scope for what I think this plug-in should do (it’s already pretty complex for an import plug-in 🤣)
> 
> I didn’t realise it was possible to specify display dimensions in embedding (or maybe it’s not?). If it is, perhaps someone will make another plug-in for you that can iterate through your files and adjust the sizes of the embeds. Try asking on the forum or discord.
> 
> In regard to your skipped and failed files, the output log you’ve shown a screenshot of is scrollable and will list all of them and describe why they were skipped or why they failed. Unfortunately you can’t get that log back so if you want to check why now I’d suggest starting a temporary new vault and importing them again, then scroll down to have a look at the end.
> 
> I wanted to export that log as a note so it could be referred to later but didn’t get the chance. I’ll do it in the coming weeks if you’d prefer to wait.
> 
> In regard to the png that’s missing, yep, that’s likely one of the failed ones.
> 
> Lastly, thanks for using my plugin! Would love it if you could follow me on threads or twitter (should help you hear about the potential update too). My handle is @daledesilva If you like generative art, I’m on instagram under the same handle.

Thanks for reply. Yes i can wait for your update and this import was also in a demo vault for testing so any way I am gonna import that again. I will next time remove all the html file myself before importing so that I don't have to scroll too much to find those failed files. And yes that idea of log file is good. It will help a lot. I will follow you both places. Thanks😊🙏
