### ISSUE TITLE
if "title" field of the json file has a special character, Obsidian crash, freeze.

### ISSUE THREAD

**Issue by ertugruluyar-github** [daledesilva/obsidian_keep-import#4] opened 2023-05-09 07:35 UTC
Obsidian doesn't accept all characters for file names.
So when you imported the file, remove special characters from "title" field of the json file.

**Comment by daledesilva** [comment] 2023-05-09 10:45
Thanks! I actually thought I had.
I’ll check when I’m back on deck and fix it :)

**Comment by daledesilva** [comment] 2023-05-10 23:00
@ertugruluyar-github I'm having a look into this and the code currently sanitises filenames so they don't contain `/` `\` or `:`
However, while those character are reported as not supported (when you try to rename a file), there are also other characters that are only half supported.

If you try and use `#` `^` `[` `]` or `|` Obsidian will let you but report that those will prevent the file from being linked to.

I think I should sanitise those as well regardless, and I assume those are what you're referring to?
Anything else I've missed?

**Comment by ertugruluyar-github** [comment] 2023-05-11 07:35
in JSON file, I have that (nested quotation marks) => "title": "aaaaaaa "bbbb" ccccc". or "\n". 
Maybe you can find the Obsidian file name rules that Obsidian doesn't accept? 
I found this -> https://forum.obsidian.md/t/list-of-not-allowed-characters-in-the-file-name-make-it-os-specific/892
And I checked on my vault ->
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/70096810/523127ac-927a-413f-9a66-f10a62404976)

**Comment by daledesilva** [comment] 2023-05-11 11:19
Thanks. Looks like you're on Windows and the illegal characters are different.
Do you mind trying to rename a file with a # and screenshot the warning you get like above?
With those two screenshots I should be able to figure out which characters to handle better (I'll put options in the settings for them)

Also, do you think you could send me the keep json that has the nested quotation marks. It looks like an illegal json format to me so I'd like to check.

**Comment by ertugruluyar-github** [comment] 2023-05-11 19:20
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/70096810/8c084125-cda5-40d3-8b73-f5cb7f9d5242)
This time, its sad that link doesn't work on file title.

**Comment by ertugruluyar-github** [comment] 2023-05-11 19:27
Github doesn't support the .json file format, so ı add an image and json text.
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/70096810/000cc8a3-52ed-4fe9-acf8-cdf7c4676736)

{"color":"DEFAULT","isTrashed":false,"isPinned":false,"isArchived":true,"textContent":"Belagat:etkili söz söylemek\nTalagat:söylemek\nMüdafaa:korumak\nSukut: sessizlik\nTebaa:halk\nAlamet: işaret\nTefekkür: düşünce\nMurakabe:denetim, kontrol\nKemal'e ulaşmak: olgunlaşmak\nYegane:tek ,en temel\nMutasavvıf: tasavvuf ilgilenen\nKall:laf\nEhemmiyet vermek:önem vermek\nMukayese: karşılaştırma\nMalum:belli olan\nİnsicanlı:etkili ahenkli\nVaiz:vaaz veren kişi\nİntiba:izlenim\nUmumiyetle: genellikle\nMuhteris: hırslı\nŞarlatan:ara bzoucu , karışıklık çıkaran\nMukedderat:kader\nBilhassa: özellikle\nCemiyet:topluluk\nMüessir olmak:etki etmek\nİzah olmak:açıklamak\nMüşterek:ortak\nMürekkep: oluşmuş, meydana gelmek\nBenim: gerçekte olmayan bir şeyi varmış gibi kabul etmek\nTenkit: eleştiri\nDimağı:Beyni, aklı\nMahirane:ustaca","title":"Mehmet Kaplan \"konuşma sanatı\"","userEditedTimestampUsec":1582972831283000,"createdTimestampUsec":1582972831283000}

**Comment by ertugruluyar-github** [comment] 2023-05-11 19:28
There is an escape character for nested quotation marks.

**Comment by daledesilva** [comment] 2023-05-13 12:36
Looking at the code you've copied in, there isn't any escape character :(

In this section it has quotation inside of quotation - which causes invalid json.
Unfortunately I won't be able to do anything about it so I might have to just add a warning so people know.

`"title":"Mehmet Kaplan "konuşma sanatı"",`

**Comment by ertugruluyar-github** [comment] 2023-05-16 08:23
Sorry for wrong info, but there is a "\n" in the some title filed.
Maybe you may add the filename of files that include nested quotation, in the warning. Because I searched those file manually and that toke lots of time.

**Comment by daledesilva** [comment] 2023-05-16 13:57
\n dictates a new line, but doesn’t escape the quotation character unfortunately.

I have a lot of error catching that does report the file name, I’ll test your file and fix it if this instance has slipped through the cracks.

Thanks!

**Comment by daledesilva** [comment] 2023-07-09 14:36
Hi @ertugruluyar-github 
Sorry for the delay on this. Unfortunately I can't fix the import to work with your file as the file is invalid JSON (The error is caused by google's export), however, I've just updated the app to not hang on problem files and show you a log of which files has issues.

The new verson is 1.0.1 and you can update from the usual Obsidian plugin directory.

I'll close this ticket, but thank you very much for reporting it and please feel free to report any other issues you find.

**Closed as completed by daledesilva** 2023-07-09 14:36 UTC

**Comment by ertugruluyar-github** [comment] 2023-07-29 17:13
Thank you, the solution is good, I think.
